apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fenster-ci-shared-data-pvc
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
