apiVersion: v1
kind: Service
metadata:
  name: fenster
  namespace: om-fenster
  labels:
    app: fenster
spec:
  selector:
    app: fenster
  ports:
    - port: 2547
      protocol: TCP
      targetPort: 2547
  type: LoadBalancer
